# file: roles/httpd/tasks/configure.yml

- name: SELinux Status Check
  command: sestatus
  notify:
    - restart netdata

- name: Ensure Netdata running
  service: name=netdata state=started enabled=yes
